version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: test_container
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=test_db
    volumes:
      - ./init_scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - data:/var/lib/postgresql/data
    restart: always

volumes:
  data: